name: Flamingo
main: adeynes\Flamingo\Flamingo
version: 0.0.1
api: 3.4.0
author: adeynes
description: Many teams. Few become flamingo after 50 minutes. Who will be the traitors?
website: https://github.com/adeynes/Flamingo